### ISSUE TITLE
Rewrite OpenApi Specification

### ISSUE THREAD

**Issue by dxloop** [dxloop/koper#1]
The current OpenAPI Specification requires rewriting to enhance clarity, improve schema organization, and provide better examples.

## Tasks
- [ ] Follow CRUD Response schema to differentiate better
- [ ] Make the schema, routes name sound more intuitive
- [ ] Adapt nested schema, which involves $ref
- [ ] Add Examples section
