### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by dxloop** [dxloop/koper#2]
Backend functionalities need to be implemented to support the application's core features. This includes setting up routes, error handling, and configuring essential components like CORS.

## Tasks

- [x] Implement Resources and Routes (Issue WIP) (#6)
- [x] Add util functions for creating error messages (#5)
- [ ] Add routes for todo functionality
- [ ] Structure different backend components e.g., services, repositories, controllers, auth
- [ ] Configure CORS
