### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by dxloop** [dxloop/koper#3]
Creating an interactive user interface, Authentication, project structuring, and implementing specific features like Todos for a quick overview of kubb features.

## Tasks

- [x] Implement Authentication Flow
- [x] Implement components for user routes
- [x] Structure project into components, services, pages, contexts, shared
- [x] Implement Todos
- [ ] Add Proxy for removing CORS for Dev Mode

**Comment by dxloop** [comment]
#10
