### ISSUE TITLE
MSW Mock Server

### ISSUE THREAD

**Issue by dxloop** [dxloop/koper#4]
The Mock Service Worker (MSW) mock server needs to be developed to facilitate frontend development, allowing for simulated API responses and data fetching during testing.

## Tasks

- [ ] Create MSW mock server package
- [ ] Integrate customized generated Faker.js data
- [ ] Integrate Fake MSW Mock Server to Frontend
